const CLOUDFLARE_ACCOUNT_ID = process.env.CLOUDFLARE_ACCOUNT_ID;
const CLOUDFLARE_API_TOKEN = process.env.CLOUDFLARE_API_TOKEN;
const CWD = process.cwd();

export { CLOUDFLARE_ACCOUNT_ID, CLOUDFLARE_API_TOKEN, CWD };
