---
name: build

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Run deploy script
        run: ./dist/deploy.cjs --help
