---
name: clean

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Desttoy Cloudflare Worker
        run: |
          export worker="${REPOSITORY/$OWNER\//}-${BRANCH}"; \
          npm run delete -- \
            --verbose \
            --name "$worker"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WRANGLER_SEND_METRICS: false
          OWNER: ${{ github.repository_owner }}
          REPOSITORY: ${{ github.repository }}
          BRANCH: ${{ github.head_ref }}
