---
name: preview

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  clean:
    if: github.event.pull_request.type == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Deploy Cloudflare Worker
        run: |
          npm run delete --verbose
