---
name: clean

on:
  pull_request:
    types:
      - closed
    branches:
      - master

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Destroy Cloudflare Worker
        run: |
          npm run delete -- --verbose
