---
name: npx

on:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Build project
        run: npm run build

      - name: Run npx
        run: ./dist/deploy.cjs -- --help
