---
name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  clean:
    if: github.event.pull_request.type == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare Worker
        run: npm run delete

  deploy:
    if: github.event.pull_request.type != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare Worker
        run: >-
          npm run deploy -- --literal GITHUB_APPLY:true
            --secret GITHUB_TOKEN:GH_TOKEN
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}

      - name: Test deployed Cloudflare worker
        run: >-
          curl -sD-
            https://${GITHUB_REPOSITORY/$GITHUB_REPOSITORY_OWNER\//}-${GITHUB_HEAD_REF}
