---
name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  preview:
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      WRANGLER_SEND_METRICS: false
      OWNER: ${{ github.repository_owner }}
      REPOSITORY: ${{ github.repository }}
      BRANCH: ${{ github.head_ref }}
    if: github.event.pull_request.type != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Set worker name envvar
        run: echo "WORKER=${REPOSITORY/$OWNER\//}-${BRANCH}" >> $GITHUB_ENV

      - name: Deploy Cloudflare Worker
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            npm run deploy -- \
              --verbose \
              --literal GITHUB_APPLY:true \
              --secret GITHUB_TOKEN:GH_TOKEN \
              --name "$WORKER"
        id: deploy

      - name: Test deployed Cloudflare worker
        run: |
          curl -sD- --retry 10 --retry-delay 0 --retry-max-time 120 --retry-all-errors ${{ steps.deploy.outputs.stdout }}

      - name: Delete Cloudflare Worker
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            npm run delete -- \
              --verbose \
              --name "$WORKER"
        id: destroy

      - name: Test destroyed Cloudflare worker
        run: >
          retries=10;
          while [ $retries -gt 0 ]; do
              retries=$((retries - 1));
              output="${{ steps.deploy.outputs.stdout }}";
              url="${output//[$'\t\r\n ']}";
              echo "testing url $url"
              return_header=$(curl -sD- $url | head -1);
              return_code=$(echo "$return_header" | awk '{print $2}');
              echo "return code is $return_code";
              if [[ "$return_code" == "404" ]]; then
                  exit 0;
              fi;
              sleep 6;
              echo "retrying ..."
          done;
          exit 1;

      - name: Deploy Cloudflare Worker
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            echo Deploying worker "$WORKER"; \
            npm run deploy -- \
              --verbose \
              --literal GITHUB_APPLY:true \
              --secret GITHUB_TOKEN:GH_TOKEN \
              --name "$WORKER"
        id: redeploy

      - name: Set worker fqdn envvar
        run: echo "FQDN=${WORKER}-test.nephelai.io" >> $GITHUB_ENV

      - name: Update Cloudflare worker with custom domain
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            echo Deploying worker "$WORKER"; \
            npm run deploy -- \
              --verbose \
              --literal GITHUB_APPLY:true \
              --secret GITHUB_TOKEN:GH_TOKEN \
              --name "$WORKER" \
              --route "$FQDN/*"

      - name: Test custom domain resolution
        run: "dig +short $FQDN @1.1.1.1"

      - name: Test custom domain endpoint
        run: |
          ADDRESS="dig +short $FQDN @1.1.1.1 | head -1"; \
          curl -sk "https://$FQDN" --resolve "$FQDN:443:$ADDRESS"

      - name: Remove custom domain from Cloudflare worker
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            echo Deploying worker "$WORKER"; \
            npm run deploy -- \
              --verbose \
              --literal GITHUB_APPLY:true \
              --secret GITHUB_TOKEN:GH_TOKEN \
              --name "$WORKER";

      - name: Test custom domain resolution
        run: "dig +short $FQDN @1.1.1.1 && exit 1 || echo custom domain removed successfully"

      - name: Record pending tasks
        run: echo Add test to ensure origin records are not pruned
