---
name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  clean:
    if: github.event.pull_request.type == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare Worker
        run: |
          npm run delete --verbose

  deploy:
    if: github.event.pull_request.type != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Deploy Cloudflare Worker
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: |
            echo npm run deploy -- --verbose --literal GITHUB_APPLY:true --secret GITHUB_TOKEN:GH_TOKEN
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WRANGLER_SEND_METRICS: false
        id: deploy

      - name: Test deployed Cloudflare worker
        run: |
          echo curl -sD- ${{ steps.deploy.outputs.stdout }}
