---
name: preview

on:
  pull_request:
    branches:
      - master

jobs:
  deploy:
    if: github.event.pull_request.type != 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Deploy Cloudflare Worker
        run: |
          export worker="${REPOSITORY/$OWNER\//}-${BRANCH}"; \
          echo Deploying worker "$worker"; \
          npm run deploy -- \
            --verbose \
            --literal GITHUB_APPLY:true \
            --secret GITHUB_TOKEN:GH_TOKEN \
            --name "$worker"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WRANGLER_SEND_METRICS: false
          OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
          REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          BRANCH: ${{ vars.GITHUB_HEAD_REF }}

      - name: Test deployed Cloudflare worker
        run: |
          curl -sD- ${REPOSITORY/$OWNER\//}-${BRANCH} \
            --retry 10 --retry-delay 0 --retry-max-time 120 --retry-all-errors
        env:
          OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
          REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          BRANCH: ${{ vars.GITHUB_HEAD_REF }}

      - name: Destroy Cloudflare Worker
        run: |
          worker="${REPOSITORY/$OWNER\//}-${BRANCH}"; \
          echo Destroying worker "$worker"; \
          npm run delete -- \
            --verbose \
            --literal GITHUB_APPLY:true \
            --secret GITHUB_TOKEN:GH_TOKEN \
            --name "$worker"
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_ACCOUNT_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          WRANGLER_SEND_METRICS: false
          OWNER: ${{ vars.GITHUB_REPOSITORY_OWNER }}
          REPOSITORY: ${{ vars.GITHUB_REPOSITORY }}
          BRANCH: ${{ vars.GITHUB_HEAD_REF }}
