---
name: publish
on:
  pull_request:
    branches:
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      string: ${{ steps.version.outputs.string }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get package version
        run: echo "string=$(jq -r .version < package.json)" >> "$GITHUB_OUTPUT"
        id: version

      - name: Debug target version
        run: echo $NPM_RELEASE
        env:
          NPM_RELEASE: ${{ steps.version.outputs.string }}

  publish:
    needs: version
    if:
      github.event.pull_request.type == 'closed' &&
      github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build --production

      - name: Publish package to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
